### PR TITLE
Userscloud Plugin Added

### PR DESCRIPTION
**Pull request by Jetleech**
The plugin works but the vinaget Leech function has to be rearranged.

### CODE REVIEW

**Comment by totaldebrid** [comment]
tested no working ?

https://userscloud.com/5oirtwd8qj4l

**Comment by Jetleech** [comment]
> tested no working ?
> 
> https://userscloud.com/5oirtwd8qj4l

Your file not downloadable. 

Vinaget needs a fix for the usercloud plugin to work.

usercloud

**Comment by totaldebrid** [comment]
tested to link on ok = https://userscloud.com/8j8fviobmn5g 

Screenshot_2020-05-17 VinaGet 3 3 LTS - Premium link generator

no working ? 
 your fix to  vinaget and support userscloud ?

**Comment by Jetleech** [comment]
Class of Vinaget needs to be fixed.. When you print the error code on the screen, you will see that the plugin is working.

**Comment by totaldebrid** [comment]
sorry i don't understand i'm not coder  :(

**Review by ltt2801 — APPROVED** [review]
Ok. I'll merge. Thank you for your support 👍

**Pull request merged**
